---
meta:
  name: sofa-core
app:
  friendlyName: Sofa
lib:
  objectName: sofaCore
  entrypoint: ./src/core/index.ts
build:
  src: ./src
  dist: ./dist
  libDist: ./lib
  types: ./types
  backend: webpack
